import React, { useRef } from 'react';
import { Database, Copy, CheckCircle, AlertCircle } from 'lucide-react';
import { toast } from 'sonner';

export function Setup() {
  const [copied, setCopied] = React.useState(false);
  const [copyError, setCopyError] = React.useState(false);
  const preRef = useRef<HTMLPreElement>(null);

  const sql = `
-- Run this script in your Supabase SQL Editor to create the necessary tables

-- 1. Users Table (Public profile info)
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  year text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Skills Table
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  skill_name text not null
);

-- 3. Goals Table
create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  goal_text text not null,
  status text check (status in ('pending', 'completed')) default 'pending'
);

-- 4. Badges Table
create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  badge_name text not null
);

-- 5. Messages Table
create table if not exists public.messages (
  id uuid default gen_random_uuid() primary key,
  sender_id uuid references public.users(id) on delete cascade not null,
  receiver_id uuid references public.users(id) on delete cascade not null,
  content text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.skills enable row level security;
alter table public.goals enable row level security;
alter table public.badges enable row level security;
alter table public.messages enable row level security;

-- Drop existing policies to avoid conflicts if re-running
drop policy if exists "Public profiles are viewable by everyone" on public.users;
drop policy if exists "Users can insert their own profile" on public.users;
drop policy if exists "Users can update their own profile" on public.users;
drop policy if exists "Skills are viewable by everyone" on public.skills;
drop policy if exists "Users can insert their own skills" on public.skills;
drop policy if exists "Messages are viewable by sender and receiver" on public.messages;
drop policy if exists "Users can send messages" on public.messages;

-- Create policies
create policy "Public profiles are viewable by everyone" on public.users for select using (true);
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.users for update using (auth.uid() = id);

create policy "Skills are viewable by everyone" on public.skills for select using (true);
create policy "Users can insert their own skills" on public.skills for insert with check (auth.uid() = user_id);

create policy "Messages are viewable by sender and receiver" on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "Users can send messages" on public.messages for insert with check (auth.uid() = sender_id);

-- AUTOMATION: Handle new user signup automatically
-- This trigger automatically creates a public user profile when a user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name, year)
  values (new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'year')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(sql);
      setCopied(true);
      setCopyError(false);
      setTimeout(() => setCopied(false), 2000);
      toast.success("SQL copied to clipboard!");
    } catch (err) {
      console.error('Failed to copy: ', err);
      setCopyError(true);
      toast.error("Auto-copy failed. Please select and copy manually.");
      
      // Fallback: Select the text
      if (preRef.current) {
          const range = document.createRange();
          range.selectNodeContents(preRef.current);
          const selection = window.getSelection();
          if (selection) {
              selection.removeAllRanges();
              selection.addRange(range);
          }
      }
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-xl shadow-lg border border-red-100 overflow-hidden">
            <div className="bg-red-50 px-6 py-4 border-b border-red-100 flex items-center">
                <Database className="h-6 w-6 text-red-600 mr-3" />
                <h1 className="text-xl font-bold text-red-800">Database Update Required</h1>
            </div>
            
            <div className="p-6">
                <p className="text-gray-700 mb-6">
                    To fix the "Row Level Security" errors, we've updated the database script. 
                    This version includes an <strong>automatic trigger</strong> to handle user creation safely.
                </p>

                <div className="bg-blue-50 rounded-lg p-4 border border-blue-100 mb-6">
                    <h3 className="font-bold text-blue-900 mb-2">Instructions:</h3>
                    <ol className="list-decimal list-inside text-blue-800 space-y-2 text-sm">
                        <li>Copy the updated SQL code below.</li>
                        <li>Go to your <strong>Supabase Dashboard</strong> {'>'} <strong>SQL Editor</strong>.</li>
                        <li>Paste the code and click <strong>Run</strong>.</li>
                    </ol>
                </div>

                <div className="relative">
                    <div className="absolute top-2 right-2 flex items-center space-x-2">
                        {copyError && (
                            <span className="text-xs text-red-500 font-medium flex items-center animate-pulse">
                                <AlertCircle className="h-3 w-3 mr-1" /> Manual Copy Required
                            </span>
                        )}
                        <button 
                            onClick={handleCopy}
                            className="inline-flex items-center px-3 py-1.5 border border-gray-300 shadow-sm text-xs font-medium rounded text-gray-700 bg-white hover:bg-gray-50 focus:outline-none"
                        >
                            {copied ? <CheckCircle className="h-4 w-4 mr-1 text-green-500" /> : <Copy className="h-4 w-4 mr-1" />}
                            {copied ? 'Copied!' : 'Copy SQL'}
                        </button>
                    </div>
                    <pre 
                        ref={preRef}
                        className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-sm font-mono leading-relaxed h-96 select-all"
                    >
                        {sql}
                    </pre>
                </div>
            </div>
        </div>
    </div>
  );
}
