-- Run this script in your Supabase SQL Editor to create the necessary tables

-- 1. Users Table (Public profile info)
create table public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  year text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Skills Table
create table public.skills (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  skill_name text not null
);

-- 3. Goals Table
create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  goal_text text not null,
  status text check (status in ('pending', 'completed')) default 'pending'
);

-- 4. Badges Table
create table public.badges (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  badge_name text not null
);

-- 5. Messages Table
create table public.messages (
  id uuid default gen_random_uuid() primary key,
  sender_id uuid references public.users(id) on delete cascade not null,
  receiver_id uuid references public.users(id) on delete cascade not null,
  content text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional but recommended for production
alter table public.users enable row level security;
alter table public.skills enable row level security;
alter table public.goals enable row level security;
alter table public.badges enable row level security;
alter table public.messages enable row level security;

-- Create simple policies (Open for this demo, restrict in production)
create policy "Public profiles are viewable by everyone" on public.users for select using (true);
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.users for update using (auth.uid() = id);

create policy "Skills are viewable by everyone" on public.skills for select using (true);
create policy "Users can insert their own skills" on public.skills for insert with check (auth.uid() = user_id);

create policy "Messages are viewable by sender and receiver" on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "Users can send messages" on public.messages for insert with check (auth.uid() = sender_id);
